# Generated by Django 6.0.4 on 2026-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_hall_metadata_and_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['name']},
        ),
    ]
